### ISSUE TITLE
Unrecognized key type name

### ISSUE THREAD

**Issue by jeremylowery** [tetractic/SK-SSH-Agent#2]
I'm trying to load a key into the SK SSH Agent that I created in Ubuntu using ssh-keygen -t ed25519-sk -O resident. The Agent gives an error of "Unrecognized key type name"

The beginning of my private key file starts with "-----BEGIN OPENSSH PRIVATE KEY-----". Is there some way I can convert this to use with SK SSH Agent? I've done similar things before with regular keys using Putty Key Gen.

**Comment by carlreinke** [comment]
SK SSH Agent loads keys in OpenSSH format, so no need to convert the key.

Support for the `sk-ssh-ed25519@openssh.com` key type is not yet implemented.  This will be coming eventually, but the security key that I currently have doesn't support it.  I have a Solo V2 on order from @solokeys, but they've been behind on fulfilling orders.

There's a list of [limitations](https://github.com/tetractic/SK-SSH-Agent#limitations) in the ReadMe.

Note that the `resident` option is also not supported, but that only applies to using the resident key capabilities (i.e., generating/downloading the key).  It shouldn't prevent you from using the key so long as you keep the private key file.

**Comment by jeremylowery** [comment]
Ah, gotcha I noticed the support for ssh-ed25519 and didn't catch the lack of the "sk-" prefix. The token I'm testing with a yubikey NFC 5. I'll recreate a new key with a different type on Ubuntu and give it a spin.

**Comment by jeremylowery** [comment]
Ok. So I got this to work using the sk-ecdsa-sha2-nistp256@openssh.com key type. When using ssh-keygen I had to use the -O resident option for it to work at all. However, the key loaded into SK SSH Agent fine and it worked perfectly. Login via PuTTY then pressed the button on the token.

**Comment by carlreinke** [comment]
`sk-ssh-ed25519@openssh.com` is supported in [v1.6](https://github.com/tetractic/SK-SSH-Agent/releases/tag/v1.6).
