### ISSUE TITLE
Hopefully more SSH clients can be supported.

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [tetractic/SK-SSH-Agent#6]
Hopefully more SSH clients can be supported.

PuTTY pageant is available with many popular SSH clients, such as MobaXterm and Tabby.
SK SSH Agent uses the PuTTY pageant interface, but it is not compatible with other clients.
Would like to be able to support other clients.

**Comment by carlreinke** [comment]
I assume those clients only support Pageant's old `WM_COPYDATA`-based IPC.  Those clients will need to upgrade to use the [named-pipe-based IPC](https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/pageant-named-pipe.html).  The old IPC is horrible, and I have no desire to implement it.
